#!/bin/bash
# Run the unit tests.

exec "${SBCL:-sbcl}" "$@" --quit \
          --eval "(asdf:load-system \"incudine-tests\" :force t)" \
          --eval "(asdf:load-system \"cudere-clm-tests\" :force t)" \
          --eval "(incudine-tests:run-tests)" \
          --eval "(cudere-clm-tests::delete-test-files)" \
          --eval "(fresh-line)"
