(declaim
 (special
  *audio-driver*
  *bounce-to-disk-guard-size*
  *c-compiler*
  *client-name*
  *default-bpm*
  *default-data-format*
  *default-header-type*
  *default-table-size*
  *edf-heap-pool-grow*
  *edf-heap-pool-size*
  *enable-jack-midi*
  *fade-curve*
  *foreign-library-directories*
  *foreign-nrt-memory-pool-size*
  *foreign-rt-memory-pool-size*
  *foreign-sample-pool-size*
  *frames-per-buffer*
  *max-buffer-size*
  *max-number-of-channels*
  *max-number-of-nodes*
  *midi-input-timeout*
  *network-buffer-size*
  *nrt-edf-heap-size*
  *nrt-priority*
  *number-of-bus-channels*
  *number-of-input-bus-channels*
  *number-of-output-bus-channels*
  *osc-buffer-size*
  *osc-max-values*
  *portaudio-input-device*
  *portaudio-output-device*
  *receiver-default-priority*
  *rt-block-size*
  *rt-edf-heap-size*
  *rt-priority*
  *sample-rate*
  *sample-type*
  *sched-policy*
  *sndfile-buffer-size*
  *sound-velocity*
  *standard-optimize-settings*
  *tlsf-block-align*
  *use-foreign-sample-p*))
