#!/bin/sh
#
# Create and install the standalone executable.
#

PREFIX="${PREFIX:-/usr/local}"
SWANK_LOADER_PATH=""
options="--noinform"
save_options=""
modules="(require \"INCUDINE\")"
before_save="(progn"
aclrepl_p="yes"
linedit_p="no"

usage()
{
        cat <<EOF
Usage: $0 [options]
Create and install the standalone executable.

  --prefix=PREFIX       install architecture-independent files in PREFIX
                        [${PREFIX}]
  --bindir=DIR          user executables [PREFIX/bin]
  --swank-loader=PATH   support for Swank server with path to swank-loader.lisp
  --without-aclrepl     do not use Allegro CL-style Read-Eval-Print Loop.
  --with-clm            use cudere-clm, the Incudine version of CLM
  --with-linedit        support for Linedit, readline-style library in CL.
  --with-fluidsynth     support for FluidSynth SoundFont synthesizer.
  --with-ladspa         support for LADSPA plugins.
  --with-lv2            support for LV2 plugins.
  --with-snd            support for the sound editor Snd.
  --with-module=NAME    load the module NAME before to create the executable.
  --save-options=OPTS   further arguments for SAVE-LISP-AND-DIE.
  --sbcl-options=OPTS   options for SBCL.
  --before-save=FORM    read and evaluate FORM before to create the executable.

EOF
        exit 1
}

add_opt()
{
        options="${options} $1"
}

add_before_save_form()
{
        before_save="${before_save} $1"
}

add_system()
{
        modules="${modules} (require \"$1\")"
}

for arg in "$@"; do
        case "${arg}" in
        --prefix=*)         PREFIX="${arg#*=}" ;;
        --bindir=*)         BINDIR="${arg#*=}" ;;
        --swank-loader=*)   SWANK_LOADER_PATH="${arg#*=}" ;;
        --without-aclrepl)  aclrepl_p="no" ;;
        --with-linedit)     linedit_p="yes" ;;
        --with-clm)         add_system "CUDERE-CLM" ;;
        --with-fluidsynth)  add_system "INCUDINE-FLUIDSYNTH" ;;
        --with-ladspa)      add_system "INCUDINE-LADSPA" ;;
        --with-lv2)         add_system "INCUDINE-LV2" ;;
        --with-snd)         add_system "INCUDINE-SND" ;;
        --with-module=*)    add_system "${arg#*=}" ;;
        --save-options=*)   save_options="${arg#*=}" ;;
        --sbcl-options=*)   add_opt "${arg#*=}" ;;
        --before-save=*)    add_before_save_form "${arg#*=}" ;;
        *)                  usage ;;
        esac
done

if [ -f "${SWANK_LOADER_PATH}" ]; then
          for m in "BSD-SOCKETS" "POSIX" "INTROSPECT" "CLTL2"; do
                  add_system "SB-${m}"
          done
          options="${options} --load ${SWANK_LOADER_PATH}"
fi

if [ ${linedit_p} = "yes" ]; then
        modules="(require :linedit) (pushnew :linedit *features*) ${modules}"
fi

if [ ${aclrepl_p} = "yes" ]; then
        modules="(require :sb-aclrepl) (pushnew :sb-aclrepl *features*) ${modules}"
fi

"${SBCL:-sbcl}" ${options} \
     --eval "(pushnew (asdf:system-source-directory :incudine) asdf:*central-registry* :test 'equal)" \
     --eval "(progn ${modules})" \
     --eval '(load (asdf:compile-file* "executable.lisp" :external-format :utf-8))' \
     --eval "${before_save})" \
     --eval "(save-lisp-and-die \"incudine\" :executable t :toplevel 'incudine::incudine-toplevel :save-runtime-options t ${save_options})" || exit

BINDIR="${BINDIR:-${PREFIX}/bin}"
readonly install_dir="${DESTDIR}${BINDIR}"

echo -n "[installing standalone executable... "
[ ! -d "${install_dir}" ] && mkdir -p "${install_dir}"
cp incudine "${install_dir}" && rm -f incudine || exit
echo "done]"
ls "${install_dir}/incudine"
